src/common/components/UserHint.tsx
src/common/input/ItemForm.tsx
src/contract/ContractEditor.tsx
src/equipmentCatalogue/EquipmentCatalogue.tsx
src/executionRequirement/PostInspectionExecutionRequirements.tsx
src/inspection/InspectionConfig.tsx
src/postInspection/PostInspectionEditor.tsx
src/procurementUnit/ProcurementUnitItem.tsx
src/report/ReportTableFilters.tsx

Fixing calendar input bug here: https://github.com/HSLdevcom/bultti/issues/89

Save button as disabled when having no changes

---

CONTRIBUTING.md
src/common/components/ExpandableSection.tsx
src/inspection/InspectionUsers.tsx

Suggestion for how to solve part of HSLdevcom/bultti#84. Not for merging.

84 expandable section click fix suggestion

---

src/common/components/Button.tsx
src/common/components/Table.tsx
src/common/icon/Trash.tsx
src/graphql.schema.json
src/inspection/inspectionDate/InsectionDateList.tsx
src/inspection/inspectionDate/InspectionDateForm.tsx
src/inspection/inspectionDate/inspectionDateQuery.ts
src/page/InspectionDatePage.tsx
src/report/ReportTableFilters.tsx
src/schema-types.ts

WIP: couldn't test if this new <RemoveButton /> works in report page because wasn't able to publish a pre-inspection...

WIP: 92 remove inspection date

---

src/departureBlock/DepartureBlockGroupItem.tsx
src/departureBlock/DepartureBlocks.tsx
src/departureBlock/blockDeparturesQuery.ts
src/departureBlock/departureBlocksCommon.ts
src/schema-types.ts

Related to HSLdevcom/bultti#100.
Remove the DayType enum from the UI code as it was removed from the schema.

Remove DayType type from schema and code.

---

src/App.tsx
src/inspection/InspectionActions.tsx
src/page/EditContractPage.tsx
src/page/OperatorContractsListPage.tsx
src/util/userRoles.ts

Relates to: https://github.com/HSLdevcom/bultti/issues/96

User role getters refactor

---

src/report/Report.tsx
src/report/reportQueries.ts

BE PR: https://github.com/HSLdevcom/bultti/pull/110
Changes related to observed departure report queries and how columnLabels are handled.

76 post inspection departures

---

CONTRIBUTING.md

What do you think?
If you have more "soft rules" of best practices to add to our ideal world, please add them!
I think I would be happy if we followed all of these rules

Added some documentation including DoR and DoD

---

src/graphql.schema.json
src/postInspection/LoadInspectionHfpData.tsx
src/schema-types.ts

Fixes HFP ready state, related to HSLdevcom/bultti#118.

118 fix hfp loading progress

---

schema.graphql
src/common/components/ExpandableSection.tsx
src/common/components/common.tsx
src/executionRequirement/PostInspectionExecutionRequirements.tsx
src/graphql.schema.json
src/graphqlClient.ts
src/postInspection/LoadInspectionHfpData.tsx
src/report/reportQueryFragments.ts
src/schema-types.ts
src/util/hasInspectionError.ts

UI updates related to HSLdevcom/bultti#72 Inspection statues.

72 post inspection statuses

---

schema.graphql
src/graphql.schema.json
src/report/reportQueryFragments.ts
src/schema-types.ts

UI updates for the unobserved departures report.

130 unobserved departures report

---

src/common/input/ItemForm.tsx
src/contract/ContractEditor.tsx
src/contract/ContractListItem.tsx
src/page/ContractPage.tsx
src/text/fi.json
src/util/promptUnsavedChanges.ts

122 contract updates

---

schema.graphql
src/equipment/equipmentQuery.ts
src/equipmentCatalogue/CatalogueEquipmentList.tsx
src/graphql.schema.json
src/schema-types.ts

Add button and mutation for updating equipment data from JORE. Update graphql schema.
Related issue: HSLdevcom/bultti#125

125 equipment emission class

---

schema.graphql
src/common/components/Table.tsx
src/equipment/AddEquipment.tsx
src/equipment/EquipmentList.tsx
src/equipment/equipmentQuery.ts
src/equipment/equipmentUtils.ts
src/equipmentCatalogue/CatalogueEquipmentList.tsx
src/equipmentCatalogue/EquipmentCatalogue.tsx
src/executionRequirement/ProcurementUnitExecutionRequirement.tsx
src/executionRequirement/RequirementEquipmentList.tsx
src/executionRequirement/executionRequirementsQueries.ts
src/graphql.schema.json
src/graphqlClient.ts
src/schema-types.ts
src/text/fi.json
src/util/emptyOrNumber.ts
src/util/useLazyQueryData.ts

UI fixes and updates related to HSLdevcom/bultti#136.
Highlights added equipment in the list.

136 add inspection vehicle

---

schema.graphql
src/contract/contractQueries.ts
src/executionRequirement/ProcurementUnitExecutionRequirement.tsx
src/executionRequirement/executionRequirementsQueries.ts
src/graphql.schema.json
src/procurementUnit/ProcurementUnitItem.tsx
src/procurementUnit/ProcurementUnitItemContent.tsx
src/procurementUnit/procurementUnitsQuery.ts
src/schema-types.ts

Move weekly meters to execution requirement for pre-inspections.
Remove procurement unit editing form.

138 refactor weekly meters

---

schema.graphql
src/equipment/AddEquipment.tsx
src/equipment/equipmentQuery.ts
src/equipment/equipmentUtils.ts
src/equipmentCatalogue/EditEquipmentCatalogue.tsx
src/equipmentCatalogue/EquipmentCatalogue.tsx
src/equipmentCatalogue/equipmentCatalogueQuery.ts
src/executionRequirement/ProcurementUnitExecutionRequirement.tsx
src/graphql.schema.json
src/procurementUnit/ProcurementUnitItemContent.tsx
src/schema-types.ts
src/text/fi.json

Equipment catalogue updates:
- Mutation for removing catalogue
- Update cache after removal
- Show "remove equipment" button only if there are some

98 equipment catalogue updates

---

schema.graphql
src/App.tsx
src/common/components/AppSidebar.tsx
src/contract/ContractEditor.tsx
src/dev/PreInspectionDevTools.tsx
src/equipment/AddEquipment.tsx
src/graphql.schema.json
src/page/ContractPage.tsx
src/page/EditContractPage.tsx
src/page/UserPage.tsx
src/preInspection/PreInspectionEditor.tsx
src/schema-types.ts
src/util/userRoles.ts

Fixes and updates to users and roles. Enable certain things only when DEBUG=true. Adjust what each role can access and see.
Issue: HSLdevcom/bultti#93

93 user account and roles

---

schema.graphql
src/common/input/ItemForm.tsx
src/graphql.schema.json
src/procurementUnit/ProcurementUnitItemContent.tsx
src/procurementUnit/procurementUnitsQuery.ts
src/report/reportQueryFragments.ts
src/schema-types.ts

151 procurement unit updates

---

schema.graphql
src/executionRequirement/PlannedExecutionStats.tsx
src/graphql.schema.json
src/postInspection/LoadInspectionHfpData.tsx
src/procurementUnit/ProcurementUnitItem.tsx
src/procurementUnit/ProcurementUnitItemContent.tsx
src/schema-types.ts
src/text/fi.json

Fix texts and labels regarding execution requirements as requested. Issue: HSLdevcom/bultti#160
Also adds update button for execution requirement stats to help with development, but this is not optimal and will probably be streamlined in HSLdevcom/bultti#150.

160 fix execution requirements

---

CONTRIBUTING.md
patches/@apollo+client+3.3.6.patch
src/common/components/Messages.tsx
src/common/components/UserRelations.tsx
src/common/components/common.tsx
src/contract/ContractEditor.tsx
src/contract/ContractUsers.tsx
src/inspection/InspectionActions.tsx
src/inspection/InspectionEditor.tsx
src/inspection/InspectionItem.tsx
src/inspection/InspectionMeta.tsx
src/inspection/InspectionReports.tsx
src/inspection/InspectionUsers.tsx
src/inspection/InspectionValidationErrors.tsx
src/inspection/InspectionsList.tsx
src/inspection/SelectInspection.tsx
src/inspection/inspectionUtils.ts
src/page/ContractPage.tsx
src/page/EditContractPage.tsx
src/page/EditInspectionPage.tsx
src/page/InspectionDatePage.tsx
src/page/InspectionReportIndexPage.tsx
src/page/InspectionReportsPage.tsx
src/page/InspectionsPage.tsx
src/page/ProcurementUnitsPage.tsx
src/page/SelectInspectionPage.tsx
src/page/UserPage.tsx
src/text/fi.json

Additional smaller UI fixes. Issue: HSLdevcom/bultti#90
- Expandable and hideable inspection meta
- Quick and dirty patch for Apollo Client to allow fast-refresh edits in Inspection views
- Minor spacing fixes to inspection page components

HSLdevcom/bultti#90 Small inspection editor style updates.

---

src/inspection/InspectionsList.tsx
src/page/EditInspectionPage.tsx
src/text/fi.json
src/util/translate.ts
src/util/useTooltip.ts

Closes https://github.com/HSLdevcom/bultti/issues/167
Noticed that there was a need for parameterization in localization in the same file. So as a bonus, now text() supports keyValueMap which was very much needed!

167 remove create inspection buttons

---

schema.graphql
src/executionRequirement/ObservedRequirementsTable.tsx
src/executionRequirement/executionRequirementsQueries.ts
src/graphql.schema.json
src/report/Report.tsx
src/report/reportQueryFragments.ts
src/schema-types.ts

Mostly schema updates for PR https://github.com/HSLdevcom/bultti/pull/185
Issue: https://github.com/HSLdevcom/bultti/issues/184

184 execution requirement values

---

schema.graphql
src/common/table/FilteredResponseTable.tsx
src/graphql.schema.json
src/postInspection/SanctionsContainer.tsx
src/schema-types.ts

UI updates for the Sanction Exceptions task. Issue: HSLdevcom/bultti#70
BE PR: https://github.com/HSLdevcom/bultti/pull/222
This PR includes schema updates and a method for matching sanction exceptions to be shown on matching sanction rows.

Sanction exceptions UI

---

src/inspection/InspectionReports.tsx
src/report/reportTotals.ts
src/text/fi.json

Closes https://github.com/HSLdevcom/bultti/issues/172
* Check from Kirsi's comment of how this is supposed to implement

172 sort raports

---

src/inspection/InspectionReports.tsx
src/report/ReportContainer.tsx

Closes https://github.com/HSLdevcom/bultti/issues/218

Show report download button for inspections in production only

---

src/equipment/EquipmentList.tsx
src/graphql.schema.json
src/procurementUnit/ProcurementUnitItemContent.tsx
src/procurementUnit/ProcurementUnits.tsx
src/schema-types.ts
src/text/fi.json

Closes https://github.com/HSLdevcom/bultti/issues/166
- procurementUnit list is now by default closed
- show grouped vehicles is by default false
- renamed "show grouped vehicles"

166 bring previously added equipment to inspection

---

src/common/table/tableUtils.tsx
src/constants.ts
src/executionRequirement/ObservedRequirementsTable.tsx
src/executionRequirement/RequirementsTable.tsx
src/postInspection/SanctionsContainer.tsx
src/report/reportTotals.ts
src/util/round.ts

Closes https://github.com/HSLdevcom/bultti/issues/265
Note: Default decimals seem to work everywhere except in sanctioning results raport where the total column seems to be a bit broken:

Fix rounding decimals 

---

src/util/formatNumber.ts

Closes https://github.com/HSLdevcom/bultti/issues/322
Fixes number display for thousand-separated numbers.

#322 Fix thousand separator.

---

src/report/DownloadReport.tsx
src/report/ExecutionRequirementsReport.tsx
src/text/fi.json

Closes https://github.com/HSLdevcom/bultti/issues/328
Just added some localization

Some localization

---

src/procurementUnit/ProcurementUnitItemContent.tsx

Closes HSLdevcom/bultti#361
Prevents non-admin users from updating the max age value. This is already blocked server-side.

#361 Prevent non-admins from updating unit max age value

---

src/equipment/AddEquipment.tsx
src/graphqlClient.ts
src/text/fi.json

Closes #HSLdevcom/bultti#360
Server PR: https://github.com/HSLdevcom/bultti/pull/378
Update the text of the equipment search button to be more contextual and show any errors arising from adding equipment to a catalogue (or execution requirement).

360 Fix adding only owned equipment 

---

src/departureBlock/DepartureBlocks.tsx
src/graphqlClient.ts
src/inspection/InspectionConfig.tsx
src/inspection/InspectionEditor.tsx
src/inspection/inspectionUtils.ts
src/text/fi.json

Closes HSLdevcom/bultti#332
Server PR: https://github.com/HSLdevcom/bultti/pull/380
Warn that departure blocks will be deleted when updating the inspection period. Localisation fixes.

332 departure block fixes

---

schema.graphql
src/equipment/EquipmentList.tsx
src/equipment/equipmentQuery.ts
src/equipment/equipmentUtils.ts
src/executionRequirement/ProcurementUnitExecutionRequirement.tsx
src/executionRequirement/RequirementEquipmentList.tsx
src/executionRequirement/executionRequirementsQueries.ts
src/graphql.schema.json
src/schema-types.ts

Schema updates arising from https://github.com/HSLdevcom/bultti/pull/384. Change all meters to kilometers.

383 Update schema

---

schema.graphql
src/common/input/SelectOperator.tsx
src/contract/ContractEditor.tsx
src/contract/contractQueries.ts
src/equipmentCatalogue/equipmentCatalogueQuery.ts
src/executionRequirement/executionRequirementsQueries.ts
src/graphql.schema.json
src/inspection/InspectionEditor.tsx
src/inspection/InspectionTimeline.tsx
src/inspection/inspectionUtils.ts
src/procurementUnit/procurementUnitsQuery.ts
src/schema-types.ts
src/state/UIStore.ts

Closes HSLdevcom/bultti#300
Schema and type updates for server PR https://github.com/HSLdevcom/bultti/pull/373

300 support multiple operator ids

---

src/page/AuthGate.tsx
src/text/fi.json

Closes HSLdevcom/bultti#376
Add user registration button to AuthGate page.

376 Add create account button

---

schema.graphql
src/graphql.schema.json
src/schema-types.ts

Schema updates for server PR: https://github.com/HSLdevcom/bultti/pull/398
Closes HSLdevcom/bultti#362

362 Update user permissions

---

src/dev/DevPage.tsx
src/graphql.schema.json
src/page/UserPage.tsx
src/schema-types.ts
src/util/userRoles.ts

Closes https://github.com/HSLdevcom/bultti/issues/449
BE PR: https://github.com/HSLdevcom/bultti/pull/450

User can now be removed from dev page. Also user.role = blocked does not exist anymore

---

src/executionRequirement/ProcurementUnitExecutionRequirement.tsx

Closes https://github.com/HSLdevcom/bultti/issues/469
BE PR: https://github.com/HSLdevcom/bultti/pull/473

Fix unit equipment list average age

---

src/graphql.schema.json
src/report/reportQueryFragments.ts
src/schema-types.ts

Closes https://github.com/HSLdevcom/bultti/issues/495
BE PR: https://github.com/HSLdevcom/bultti/pull/496

Added routeLength column

---

.env.production
cypress/integration/post_inspection_create_spec.js
cypress/integration/pre_inspection_create_spec.js
cypress/integration/report/equipment_color_violation_spec.js
cypress/support/commands.js
cypress/support/expectedEntityCounts.js
cypress/support/index.js
cypress/support/preInspectionCommands.js
src/common/table/FilteredResponseTable.tsx
src/common/table/TableFiltersControl.tsx
src/common/table/TablePagingControl.tsx
src/contract/ContractEditor.tsx
src/dev/DevPage.tsx
src/graphql.schema.json
src/postInspection/EditSanctions.tsx
src/schema-types.ts
src/text/fi.json

Closes https://github.com/HSLdevcom/bultti/issues/465
BE PR: https://github.com/HSLdevcom/bultti/pull/475
IMPORTANT: before clicking "create test data" in this PR, make sure you remove all test data in Master branch.

Color violation tests

---

cypress/integration/procurement_units_spec.js
package.json
src/common/input/ItemForm.tsx
src/procurementUnit/ProcurementUnitItemContent.tsx

Closes https://github.com/HSLdevcom/bultti/issues/491
BE PR: https://github.com/HSLdevcom/bultti/pull/504
Also added E2E to test this. Had to also fix a render bug; not showing things if loader is on the screen (otherwise form data is bugged and E2E tests fail)

491 fix remove unit option
