HSLdevcom/bultti-ui

- src/contract/ContractEditor.tsx
Closes https://github.com/HSLdevcom/bultti/issues/51
Instead of showing the mutation request result error, show errors from the mutation hooks. This is more dynamic and reactive and doesn't require local state for the error.
Also, it should show errors from both the create and update mutations.
> Show errors from contract mutation hooks

- CONTRIBUTING.md
- src/App.tsx
- src/common/components/AppSidebar.tsx
- src/graphql.schema.json
- src/inspection/inspectionDate/InsectionDateList.tsx
- src/inspection/inspectionDate/InspectionDateForm.tsx
- src/inspection/inspectionDate/inspectionDateQuery.ts
- src/page/InspectionDatePage.tsx
- src/schema-types.ts
- src/text/fi.json
**Made a new card: InspectionForms: date options https://github.com/HSLdevcom/bultti/issues/95**
(new card is needed because minStartDate, inspectionStartDate and inspectionEndDate are to be removed)
**Suggestion: new card -> https://github.com/HSLdevcom/bultti/issues/96**
Refactor like this:
```
export function getIsUserAdmin(): boolean {
let [user] = useStateValue('user')
return requireUser(user) && user?.role === UserRole.Admin
}
```
(also in backend + other methods too. Move role checking into backend)
**Suggestion 2: new card -> ?**
Validations by using some easilly configurable models like in jore-map-ui:
https://github.com/HSLdevcom/jore-map-ui/blob/develop/src/models/validationModels/lineValidationModel.ts
**Suggestion 3: new card -> ?**
We need a way to pass dates to the calendar …
> Inspection date range entity & resolvers

- src/common/input/SelectDate.tsx
- src/inspection/InspectionConfig.tsx
Unfortunately opening calendar from the whole input component wasn't possible (tried using ref). If we want this feature (and also possibility to write the date by hand), we should start using some calendar library.
At least date is now properly passing to parent component as soon as it's changed
> 89 Calendar input improvements

- src/equipmentCatalogue/EquipmentCatalogue.tsx
- src/inspection/InspectionConfig.tsx
- src/procurementUnit/ProcurementUnitFormInput.tsx
- src/procurementUnit/ProcurementUnitItem.tsx
I noticed some forms have "old" states for input values, which were used to determine if the form is dirty. Since the "old" state is already available in each component as the main entity that the component is rendering, a separate old state is not needed.
Generally, state should be used sparingly and only when necessary.
> HSLdevcom/bultti#88 Remove and refactor redundant old-states from forms.

- CONTRIBUTING.md
- src/contract/ContractEditor.tsx
- src/graphql.schema.json
- src/page/ContractPage.tsx
- src/page/SelectInspectionPage.tsx
- src/preInspection/PreInspectionEditor.tsx
- src/procurementUnit/ProcurementUnitItem.tsx
- src/procurementUnit/ProcurementUnitItemContent.tsx
- src/procurementUnit/ProcurementUnits.tsx
- src/procurementUnit/procurementUnitsQuery.ts
- src/schema-types.ts
- src/text/fi.json
- src/util/urlValue.ts
- src/util/useQueryData.ts
Relates to: https://github.com/HSLdevcom/bultti/issues/105
1. Procurement units are not listed before the contract is saved
* Showing "Ei ladattua tiedostoa" text when creating new
2.Editing procurement unit will make the unit's contract info disappear from the expandable box header
To fix this, startDate and endDate needed to be added to the single procurementQuery.
A better solution could be to remove currentContracts and make a resolver in ContractResolver to get them. I think that is out of the scope this card though, card -> ?
Btw, I don't really like that startDate and endDate are transfered through the whole component tree, that's ugly. What if we used a store / react context for each page so that you could set a variable there to be accessed from anywhere in the same page?
Card -> …
> 105 fix procurement unit issues 2

- src/common/components/DateRangeDisplay.tsx
- src/common/input/Dropdown.tsx
- src/common/input/SelectDate.tsx
- src/common/input/SelectOperator.tsx
- src/contract/ContractListItem.tsx
- src/dev/PreInspectionDevTools.tsx
- src/executionRequirement/PostInspectionExecutionRequirements.tsx
- src/inspection/InspectionApprovalSubmit.tsx
- src/inspection/InspectionConfig.tsx
- src/inspection/InspectionItem.tsx
- src/inspection/InspectionTimeline.tsx
- src/inspection/InspectionsList.tsx
- src/inspection/SelectInspection.tsx
- src/inspection/inspectionSelectDates.tsx
- src/page/EditContractPage.tsx
- src/page/InspectionDatePage.tsx
- src/page/InspectionReportIndexPage.tsx
- src/page/ProcurementUnitsPage.tsx
- src/postInspection/LoadInspectionHfpData.tsx
- src/text/fi.json
- src/util/formatDate.ts
- src/util/strval.ts
- src/util/useSeasons.ts
Relates to: https://github.com/HSLdevcom/bultti/issues/95
BE PR: https://github.com/HSLdevcom/bultti/pull/169
When creating post inspection results, it's now done by filtering the date options. Other way would be to add possibility to the dropdown to make an item unselectable but maybe leave it for later (make a card if someone proposes it later). Here it would help if the props to our dropdown were typed e.g. IDropdownItem: { key, label, isDisabled }
~~Hmm, I wish we could make InputLabel take hint text as props. Then u could pass hint to a  dropdown that passes it to InputLabel. Make a new card of making <InputLabel /> use <UserHint /> (that wasn't quite simple so I didn't do it here)~~
- ~~and when this is done, one could add a hint next to dropdown's label if creating pre inspection: …
> WIP: 95 fix date fields into dropdown

- src/common/components/form.tsx
- src/common/input/Dropdown.tsx
- src/common/input/Input.tsx
- src/inspection/InspectionMeta.tsx
- src/inspection/inspectionSelectDates.tsx
- src/postInspection/LoadInspectionHfpData.tsx
- src/text/fi.json
Closes https://github.com/HSLdevcom/bultti/issues/174
Now Input, InputLabel and Dropdown supports hintText param. I think we can make other components support hintText too as we go (should be easy since InputLabel now supports it)
Btw I sorted those Input params. Imo we don't need to nitpick param order in PR's but I wish you could try to put them in some specific order. I usually list the core ones first and then "not so core" props. And I also like to put methods lastly. Could even document this to conventions as "not strict rules" or smth
> 174 hint param to support input label

- package.json
- src/common/components/Button.tsx
- src/common/components/Table.tsx
- src/equipment/EquipmentList.tsx
- src/equipmentCatalogue/CatalogueEquipmentList.tsx
- src/report/ListReport.tsx
- src/report/Report.tsx
- src/report/ReportPaging.tsx
- src/text/fi.json
- yarn.lock
Closes: https://github.com/HSLdevcom/bultti/issues/85
CSS Note: I wish I could disable hover for options with selectedPageOptionStyles style object. Didn't figure out an easy way to do that.
How the idea works:
You can pass to <Table>:
visibleRowCountOptions={[]} // to show all elements
visibleRowCountOptions={[5, 10]} // to show 5 / 10 elements per page options
visibleRowCountOptions={undefined} // when not passing visibleRowCountOptions, default 10, 20, 50 options are shown
selectedRowCountOption={20} // option 20 is selected by default
selectedRowCountOption={19} // throws an error if option 19 is not found
Note: Logic changed a bit when refactored remove button related things:
{!isEditingRow && removeItem && ( <RowRemoveButton>...
--> is now just
{onRemoveRow && ( <RowRemoveButton>... …
> 85 table component fixes

- src/common/components/Loading.tsx
- src/common/components/Messages.tsx
- src/common/components/Typography.tsx
- src/common/input/Dropdown.tsx
- src/common/input/Input.tsx
- src/departureBlock/DepartureBlocks.tsx
- src/executionRequirement/PlannedExecutionStats.tsx
- src/executionRequirement/PreInspectionExecutionRequirements.tsx
- src/executionRequirement/ProcurementUnitExecutionRequirement.tsx
- src/index.css
- src/inspection/InspectionConfig.tsx
- src/inspection/InspectionEditor.tsx
- src/inspection/InspectionUsers.tsx
- src/inspection/inspectionSelectDates.tsx
- src/text/fi.json
Closes: https://github.com/HSLdevcom/bultti/issues/150
Found 2 bugs and fixed them:
* Bug 1: Pre inspection name startDate / endDate saving didnt work
* The reason for this was simple. Found from BE inspectionResolver: "Allow only name update if inspection is not in draft state."
--> Had to just disable editing dates if not in DRAFT mode
* Bug 2: When date saved, isDirty didn't get updated (save button was active even after saving)
Removed update buttons from Inspection pages
* yes, didn't remove procurementUnit update button because it's being used at procurementUnit page and it does have a job there - instead that update button should be moved to the header in procurementUnit page (should I do it here?)
Note: also refactored updateInspectionCb - removed useless code
* the idea in a save …
> 150 inspection update button fixes

- .gitignore
- src/graphql.schema.json
- src/inspection/inspectionDate/inspectionDateQuery.ts
- src/inspection/inspectionSelectDates.tsx
- src/schema-types.ts
Closes https://github.com/HSLdevcom/bultti/issues/206
* When merged, this card can be removed: https://github.com/HSLdevcom/bultti/issues/224
* I removed check from filtering observed date options "Only dates that are older than 1 month are valid"
* As now the first inspection date is selected by default, I see no reason to filter here (because invalid value could still end up as being selected because of the default selection). Instead, before prosessing inspections, we should validate that the currently selected inspectionStartDate & inspectionEndDate are valid. In which card should we document this change?
* If date range doesnt exist for a season creating post inspection, an error is thrown. Card to localize this (and other) messages: https://github.com/HSLdevcom/bultti/issues/227
> 206 inspection date range selection fixes

- .gitignore
- src/equipmentCatalogue/EditEquipmentCatalogue.tsx
- src/inspection/InspectionConfig.tsx
- src/util/promptUnsavedChanges.ts
Closes https://github.com/HSLdevcom/bultti/issues/208
Prompt bugs that are fixed here:
1) Insert a new procurementUnit list -> prompts if leaving page
2) Go and create a new contract -> save -> prompts if leaving page
3) Inspection name change -> doesn't prompt if unsaved changes
(didn't find any other prompt issuses while testing - now everything seem to work!)
NOTE: when creating new inspection, it prompts about unsaved changes if trying to leave. That is due to name being dirty when it shouldnt be. It will be fixed in my date dropdown PR! So dont mind about that
> 208 fix unsaved changes prompt

- src/text/fi.json
- src/util/useAuth.ts
Closes https://github.com/HSLdevcom/bultti/issues/198
* Steps for thesting can be found from the issue description.
* when user is logged and then blocked from HSL ID, he can still do things like saving (until he presses f5)
* there is nothing we can do about this (or we could fetch groups from HSL ID with every request but that's not what we want to do)
* BUT if you make user.role = 'BLOCKED' by hand in DB, then saving should be prevented -> test that this works (works for me at least)
* when user is blocked, it gives 400 (Bad Request) and that seems to crash the app. Maybe not in scope of this task to fix it but maybe it should be fixed somewhere (or here)?
* Note: from now on, user must be 'blocked' in HSL ID (if making it only 'blocked' in DB, it will be overridden when the user …
> 198 Ability to lock user in HSL ID

- src/common/components/AppSidebar.tsx
- src/common/components/GlobalOperatorFilter.tsx
- src/common/components/GlobalSeasonFilter.tsx
- src/common/components/SidebarStyledDropdown.tsx
- src/inspection/InspectionActions.tsx
- src/inspection/InspectionConfig.tsx
- src/inspection/InspectionEditor.tsx
- src/inspection/SelectInspection.tsx
- src/inspection/inspectionSelectDates.tsx
- src/inspection/inspectionUtils.ts
- src/page/EditInspectionPage.tsx
- src/text/fi.json
Closes https://github.com/HSLdevcom/bultti/issues/230
As a small bonus, added inspection date range (we've had discussion that it's ok to do):
Tried to override the style at: GlobalSeasonFilter.tsx
with:
const StyledDropdown = styled(SidebarStyledSelect)`
padding-bottom: 0;
`
but got this error:
ReferenceError: Cannot access 'SidebarStyledSelect' before initialization
so that's why I made a separate styled element in AppSidebar
> 230 prevent season switch when opening inspection

- src/common/table/tableUtils.tsx
- src/executionRequirement/ObservedRequirementsTable.tsx
- src/executionRequirement/RequirementsTable.tsx
- src/report/reportTotals.ts
- src/util/formatNumber.ts
Closes https://github.com/HSLdevcom/bultti/issues/216
I'd prefer to just make one util: getThousandSeparatedNumber() to handle all 3 input types: input: number | string | Big
but to implement that, you have to check if input type is Big, but how to do that? This didn't work: typeof input === 'Big'
> 216 use thousand separator in tables

- src/common/table/FilteredResponseTable.tsx
- src/common/table/Table.tsx
- src/common/table/TableCell.tsx
- src/common/table/TableRow.tsx
- src/common/table/tableUtils.tsx
- src/equipment/EquipmentList.tsx
- src/executionRequirement/PlannedExecutionStats.tsx
- src/index.css
- src/report/ReportContainer.tsx
- src/report/reportCellHighlightColor.ts
Closes https://github.com/HSLdevcom/bultti/issues/271
Review fixes left from earlier PR: https://github.com/HSLdevcom/bultti-ui/pull/91
Rowhighlight should work, if there is row highlight, it currently overrides cell highlight. Well it could be done vise versa... but at least for the current setup works.
> Review fixes, getRowHighlightColor + getCellHighlightColor now work

- schema.graphql
- src/App.tsx
- src/common/components/AppSidebar.tsx
- src/common/table/Table.tsx
- src/equipment/equipmentQuery.ts
- src/equipmentCatalogue/CatalogueEquipmentList.tsx
- src/equipmentCatalogue/EquipmentCatalogue.tsx
- src/graphql.schema.json
- src/inspection/InspectionActions.tsx
- src/inspection/InspectionConfig.tsx
- src/inspection/InspectionEditor.tsx
- src/inspection/InspectionItem.tsx
- src/inspection/SelectInspection.tsx
- src/inspection/inspectionUtils.ts
- src/page/EditContractPage.tsx
- src/page/EditInspectionPage.tsx
- src/page/InspectionsPage.tsx
- src/page/ProcurementUnitsPage.tsx
- src/page/SelectInspectionPage.tsx
- src/postInspection/SanctionsContainer.tsx
- src/preInspection/PreInspectionEditor.tsx
- src/procurementUnit/ProcurementUnitItem.tsx
- src/procurementUnit/ProcurementUnitItemContent.tsx
- src/procurementUnit/ProcurementUnits.tsx
- src/schema-types.ts
- src/text/fi.json
- src/util/userRoles.ts
Closes https://github.com/HSLdevcom/bultti/issues/333
Note: currently only admins can accept pre and post inspections. We'll implement double accept later where also operator can accept their owns inspections
Questions:
* Should I remove those methdos marked with TODO: remove? Note: I don't want this PR to be merged with any new TODO's so something needs to be done with them (I found like 5-8 unused resolvers)
* Is guardPlannedUnitExecutionRequirementResolvers OK that it has allowedRoles: [UserRole.HSL]?
* refreshEquipmentInCatalogueMutation: this was OK to be available for all roles
* Shouldn't we remove DEV Load sanctions button from post inspection's page? We have devResolver for that, if ever want to test running some functions in backend.
* "Sopimuksessa mukana toggle" - is the …
> 333 role fixes according to role matrix

- src/report/DownloadReport.tsx
Closes HSLdevcom/bultti#327
Fix to make the "report is empty" error show for the user when trying to download an empty report instead of giving a corrupted Excel file.
Server PR:
> 327 Fix empty excel report error

- schema.graphql
- src/graphql.schema.json
- src/report/reportQueryFragments.ts
- src/schema-types.ts
Closes HSLdevcom/bultti#293
Schema updates to include the new trunk route field of equipment color report rows.
Server PR: https://github.com/HSLdevcom/bultti/pull/381
> 293 Update equipment color report schema

- schema.graphql
- src/executionRequirement/ProcurementUnitExecutionRequirement.tsx
- src/graphql.schema.json
- src/graphqlClient.ts
- src/inspection/InspectionActions.tsx
- src/inspection/InspectionCard.tsx
- src/inspection/InspectionConfig.tsx
- src/inspection/InspectionIndexItem.tsx
- src/inspection/InspectionPreview.tsx
- src/inspection/InspectionsList.tsx
- src/inspection/SelectInspection.tsx
- src/inspection/inspectionQueries.ts
- src/page/InspectionReportIndexPage.tsx
- src/schema-types.ts
Closes HSLdevcom/bultti#291
Server PR: https://github.com/HSLdevcom/bultti/pull/382
Hide the "production period" date inputs in the post-inspection config form. Schema updates.
> 291 inspection date updates

- src/common/components/AppSidebar.tsx
- src/common/components/Tabs.tsx
Closes HSLdevcom/bultti#437
Fixes inspection edit tab navigation, where the UI would disappear if the current tab disappears. Also fixes sidebar link to the user page.
Server PR: https://github.com/HSLdevcom/bultti/pull/438
> 148 fix page routes

- schema.graphql
- src/App.tsx
- src/common/components/AppSidebar.tsx
- src/graphql.schema.json
- src/page/StatusPage.tsx
- src/schema-types.ts
- src/text/fi.json
- src/util/userRoles.ts
Closes HSLdevcom/bultti#397
Add a maintenance nav section to the sidebar containing the Dev Page (for devs) and a Status page. The status page contains a Worker Status section listing currently running worker jobs.
Server PR: https://github.com/HSLdevcom/bultti/pull/439
> 397 worker status page

- src/executionRequirement/ProcurementUnitExecutionRequirement.tsx
- src/executionRequirement/RequirementEquipmentList.tsx
- src/text/fi.json
Closes HSLdevcom/bultti#326
Hides equipment remove button in execution requirements for operator users.
Server PR: https://github.com/HSLdevcom/bultti/pull/436
> 326 Block operators from removing execution requirement equipment

- src/util/isNumeric.ts
- src/util/useAuth.ts
Closes https://github.com/HSLdevcom/bultti/issues/456
* First problem solution: remove auth token from clear local storage if login fails so that user does not have to manually reset application memory from browser's console. Hopefully this solves the problem.
* So the second problem was that when logging in and code param started with a number, isNumber thought that the string was a number and tried to parse it. The fix for isNumber check taken from here:
https://stackoverflow.com/a/50376498/4282381
> 456 logging in fixes
